### ISSUE TITLE
Sensitivity <1 is not working within interactive knob builder page

### ISSUE THREAD

**Issue by ColinBD** [ColinBD/JSAudioKnobs#3]
Trying the interactive knob builder and I find that if I set a sensitivity below 1 (as the instructions say I should be able to do), the knob does not turn and the object text printed on screen states '0' for values like 0.7. Note, this does not impact the main library as the JSFiddle (linked from the readme) works fine with sensitivity <1.

**Comment by ColinBD** [comment]
The issue was caused by javascript within the demo's html doc, so it was not an issue with the main library. I changed a 'parseInt' to 'parseFloat().toFixed(1)' and thus sensitivity can now be set to one decimal place including <1 values like 0.5. The knob would then need significant mouse movements to produce small changes in knob value (as expected).

**Comment by ising4jesus** [comment]
I hadn't looked that closely to notice that it was just the demo code at fault.  That's good to know!
As long as it includes the full scale from 0% to 100% for the knob positions, I'm happy!  



Thanks again for the response!


- Brian
re:






---- On Mon, 24 Apr 2023 05:05:56 -0500 Colin Bone Dodds ***@***.***> wrote ---





The issue was caused by javascript within the demo's html doc, so it was not an issue with the main library. I changed a 'parseInt' to 'parseFloat().toFixed(1)' and thus sensitivity can now be set to one decimal place including <1 values like 0.5. The knob would then need significant mouse movements to produce small changes in knob value (as expected).
